mpic/blueprints/ajax.py
'''
ajax蓝本类
'''

from flask import render_template, jsonify, Blueprint
from flask_login import current_user

from mpic.models import User,Notification,Photo
from mpic.notifications import push_follow_notification,push_collect_notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)

@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user=User.query.get_or_404(user_id)
    count=user.followers.count()-1
    return jsonify(count=count)

@ajax_bp.route('/follow/<username>',methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:
        return jsonify(message='需要登录才能继续操作'),403
    if not current_user.confirmed:
        return jsonify(message='账号需要验证后方可继续'),400
    if not current_user.can('FOLLOW'):
        return jsonify(message='你没有这个权限！'),403

    user=User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        return jsonify(message='您已经关注过此人了'),400

    current_user.follow(user)
    if user.receive_collect_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return jsonify(message='关注成功！')


@ajax_bp.route('/unfollow/<username>',methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:
        return jsonify(message='请先登录！'),403
    user=User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        return jsonify(message='还没有关注此人'),400
    current_user.unfollow(user)
    return jsonify(message='取关成功！')


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='需要登录！'),403

    count=Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)

@ajax_bp.route('/<int:photo_id>/followers-count')
def collectors_count(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    count = len(photo.collectors)
    return jsonify(count=count)

@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='需要登录。'), 403

    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        return jsonify(message='还没有收藏！'), 400

    current_user.uncollect(photo)
    return jsonify(message='已取消收藏！')

@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='需要登录！'), 403
    if not current_user.confirmed:
        return jsonify(message='需要先激活您的账户！'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='没有权限！'), 403

    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        return jsonify(message='已经收藏过了！'), 400

    current_user.collect(photo)
    if current_user != photo.author and photo.author.receive_collect_notification:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return jsonify(message='照片收藏成功！')

mpic/blueprints/auth.py
'''
账户模块蓝本
'''
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

from mpic.extensions import db
from mpic.forms.auth import LoginForm, RegisterForm, ForgetPasswordForm, ResetPasswordForm
from mpic.emails import send_confirm_email, send_reset_password_email
from mpic.models import User
from mpic.settings import Operations
from mpic.utils import generate_token, validate_token, redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('登录成功.', 'info')
                return redirect_back()
            else:
                flash('你的账号已被封禁。', 'warning')
                return redirect(url_for('main.index'))
        flash('错误的email或者密码！', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data.lower()
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.set_password(password)
        user.confirmed=True
        db.session.add(user)
        db.session.commit()
        #token = generate_token(user=user, operation='confirm')
        #send_confirm_email(user=user, token=token)
        #flash('确认邮件已经发送至您的邮箱。', 'info')
        flash('注册成功！', 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))
    if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
        flash('账号已激活', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('不被许可的token', 'danger')
        return redirect(url_for('.resend_confirm_email'))


@auth_bp.route('/resend-confirm-emails')
@login_required
def resend_confirm_email():
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    token = generate_token(user=current_user, operation=Operations.CONFIRM)
    send_confirm_email(user=current_user, token=token)
    flash('一封新的激活邮件已经发送至您的邮箱。', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('一封验证邮件已经发送至您的邮箱。', 'info')
            return redirect(url_for('.login'))
        flash('错误的Email。', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            return redirect(url_for('main.index'))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
                          new_password=form.password.data):
            flash('密码已更改。', 'success')
            return redirect(url_for('.login'))
        else:
            flash('token验证有误，请重新尝试此操作。', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

@auth_bp.route('/re-authenticate',methods=['GET','POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('main.index'))

    form=LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()
        return redirect_back()
    return render_template('auth/login.html',form=form)

mpic/blueprints/user.py
'''
用户主页蓝本类
'''
from flask import Blueprint, render_template, current_app, request, flash, redirect, url_for
from flask_login import login_required, current_user, fresh_login_required,logout_user

from mpic.models import User, Photo, Collect
from mpic.decorators import confirm_required, permission_required
from mpic.emails import send_confirm_email
from mpic.extensions import db, avatars
from mpic.settings import Operations
from mpic.utils import redirect_back, generate_token, validate_token, flash_errors
from mpic.notifications import push_follow_notification
from mpic.forms.user import EditProfileForm, UploadAvatarForm, CropAvatarForm, ChangeEmailForm, \
    ChangePasswordForm, NotificationSettingForm, PrivacySettingForm, DeleteAccountForm

user_bp = Blueprint('user', __name__)


@user_bp.route('/<username>')
def index(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user == current_user and user.locked:
        flash('你的账户已被锁定','danger')
    if user== current_user and not user.active:
        logout_user()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTO_PER_PAGE']
    pagination = Photo.query.with_parent(user).order_by(Photo.timestamp.desc()).paginate(page, per_page)
    photos = pagination.items
    return render_template('user/index.html', user=user, pagination=pagination, photos=photos)


@user_bp.route('/<username>/collections')
def show_collections(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTO_PER_PAGE']
    pagination = Collect.query.with_parent(user).order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('user/collections.html', user=user, pagination=pagination, collects=collects)


@user_bp.route('follow/<username>', methods=['POST'])
@login_required
@confirm_required
@permission_required('FOLLOW')
def follow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        flash('已经关注过了', 'info')
        return redirect(url_for('.index', username=username))

    current_user.follow(user)
    flash('关注成功！', 'success')
    if user.receive_follow_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return redirect_back()


@user_bp.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        flash('还没有关注。。', 'info')
        return redirect(url_for('.index', username=username))

    current_user.unfollow(user)
    flash('取关成功！', 'success')
    return redirect_back()


@user_bp.route('/<username>/followers')
def show_followers(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['USER_PER_PAGE']
    pagination = user.followers.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/followers.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/<username>/following')
def show_following(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['USER_PER_PAGE']
    pagination = user.following.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/following.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/settings/avatar')
@login_required
@confirm_required
def change_avatar():
    upload_form = UploadAvatarForm()
    crop_form = CropAvatarForm()
    return render_template('user/settings/change_avatar.html', upload_form=upload_form, crop_form=crop_form)


@user_bp.route('/settings/avatar/upload', methods=['POST'])
@login_required
@confirm_required
def upload_avatar():
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)
        current_user.avatar_raw = filename
        db.session.commit()
        flash('上传完成，请裁剪后继续。', 'success')
    flash_errors(form)
    return redirect(url_for('.change_avatar'))


@user_bp.route('/settings/avatar/crop', methods=['POST'])
@login_required
@confirm_required
def crop_avatar():
    form = CropAvatarForm()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(current_user.avatar_raw, x, y, w, h)
        current_user.avatar_s = filenames[0]
        current_user.avatar_m = filenames[1]
        current_user.avatar_l = filenames[2]
        db.session.commit()
        flash('头像保存成功！', 'success')

    flash_errors(form)
    return redirect(url_for('.change_avatar'))


@user_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit() and current_user.validate_password(form.old_password.data):
        current_user.set_password(form.password.data)
        db.session.commit()
        flash('密码修改成功！', 'success')
        return redirect(url_for('.index', username=current_user.username))
    return render_template('user/settings/change_password.html', form=form)


@user_bp.route('/settings/change-emails', methods=['GET', 'POST'])
@fresh_login_required
def change_email_request():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        #token = generate_token(user=current_user, operation=Operations.CHANGE_EMAIL, new_email=form.email.data.lower())
        #send_confirm_email(to=form.email.data, user=current_user, token=token)
        #flash('确认邮件已发送至您的新邮箱！', 'info')
        return redirect(url_for('.index', username=current_user.username))
    return render_template('user/settings/change_email.html', form=form)


@user_bp.route('/change-emails/<token>')
@login_required
def change_email(token):
    if validate_token(user=current_user, token=token, operation=Operations.CHANGE_EMAIL):
        flash('邮箱修改完成！', 'success')
        return redirect(url_for('.index', username=current_user.username))
    else:
        flash('不被允许的密钥！', 'warning')
        return redirect(url_for('.change_email_request'))


@user_bp.route('/settings/notification', methods=['GET', 'POST'])
@login_required
def notification_setting():
    form = NotificationSettingForm()
    if form.validate_on_submit():
        current_user.receive_collect_notification = form.receive_collect_notification.data
        current_user.receive_comment_notification = form.receive_comment_notification.data
        current_user.receive_follow_notification = form.receive_follow_notification.data
        db.session.commit()
        flash('设置已保存！', 'success')
        return redirect(url_for('.index', username=current_user.username))
    form.receive_collect_notification.data = current_user.receive_collect_notification
    form.receive_comment_notification.data = current_user.receive_comment_notification
    form.receive_follow_notification.data = current_user.receive_follow_notification
    return render_template('user/settings/edit_notification.html', form=form)

@user_bp.route('/settings/privacy',methods=['GET','POST'])
@login_required
def privacy_setting():
    form=PrivacySettingForm()
    if form.validate_on_submit():
        current_user.public_collections=form.public_collections.data
        db.session.commit()
        flash('设置已保存','success')
        return redirect(url_for('.index',username=current_user.username))
    form.public_collections.data=current_user.public_collections
    return render_template('user/settings/edit_privacy.html',form=form)

@user_bp.route('/settings/account/delete',methods=['GET','POST'])
@fresh_login_required
def delete_account():
    form=DeleteAccountForm()
    if form.validate_on_submit():
        db.session.delete(current_user._get_current_object())
        db.session.commit()
        flash('再见来不及挥手！','success')
        return redirect(url_for('main.index'))
    return render_template('user/settings/delete_account.html',form=form)

@user_bp.route('/settings/profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.bio = form.bio.data
        current_user.website = form.website.data
        current_user.location = form.location.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect(url_for('.index', username=current_user.username))
    form.name.data = current_user.name
    form.username.data = current_user.username
    form.bio.data = current_user.bio
    form.website.data = current_user.website
    form.location.data = current_user.location
    return render_template('user/settings/edit_profile.html', form=form)

mpic/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %}{% endblock %} - Albumy</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% endblock styles %}
    {% endblock head %}
</head>

<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="{{ url_for('static', filename='2.jpg') }}" width="50" height="50"
                     class="d-inline-block" alt="" style="margin-right: 10px">
                <span class="heading">Mpic</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.index', '主页') }}
                    {{ render_nav_item('main.explore', '探索') }}
                    <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search') }}">
                        <input type="text" name="q" class="form-control mr-sm-1" placeholder="照片，用户或是标签"
                               required>
                        <button class="btn btn-light my-2 my-sm-0" type="submit">
                            <span class="oi oi-magnifying-glass"></span>
                        </button>
                    </form>
                </div>
                <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('main.show_notifications', filter='unread') }}">
                         <span class="oi oi-bell"></span>
                         <span id="notification-badge"
                               class="{% if notification_count == 0 %}hide{% endif %} badge badge-danger badge-notification"
                               data-href="{{ url_for('ajax.notifications_count') }}">{{ notification_count }}</span>
                     </a>
                    <a class="nav-item nav-link" href="{{ url_for('main.upload') }}" title="上传">
                        <span class="oi oi-cloud-upload"></span>&nbsp;&nbsp;
                    </a>
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            <img class="avatar-xs"
                                 src="{{ url_for('main.get_avatar', filename=current_user.avatar_s) }}">
                            <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <h6 class="dropdown-header">当前用户： {{ current_user.username }}</h6>
                            <a class="dropdown-item" href="{{ url_for('user.index', username=current_user.username) }}">
                                <span class="oi oi-person"></span> 我的个人主页
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('user.edit_profile') }}">
                                <span class="oi oi-cog"></span> 个人设置
                            </a>
                            {% if current_user.can('MODERATE') %}
                                <a class="dropdown-item" href="{{ url_for('admin.index') }}">
                                    <span class="oi oi-dashboard"></span> 控制台
                                </a>
                            {% endif %}
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                <span class="oi oi-power-standby"></span> 注销
                            </a>
                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">登录</a>&nbsp;&nbsp;
                    <a class="btn btn-primary" href="{{ url_for('auth.register') }}">加入Mpic！</a>
                {% endif %}
                </div>
            </div>
        </div>
    </nav>
{% endblock %}

<main>
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
        {% block footer %}
            <footer>
                <p class="float-left">
                    <small>灵感与思路来自开源网站和相关教程，欢迎与我交流FLask世界的一切！
                        <a href="http://182.61.16.104/">Marc's Blog</a> -
                        <a href="https://github.com/markxvii">GitHub</a> -
                    </small>
                </p>
            </footer>
        {% endblock %}
    </div>
</main>
<div id="toast"></div>

{% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script type="text/javascript">
        var csrf_token="{{ csrf_token() }}";
        {% if current_user.is_authenticated %}
            var is_authenticated=true;
        {% else %}
            var is_authenticated=false;
        {% endif %}
    </script>
{% endblock %}
</body>
</html>

mpic/templates/macros.html
<!--渲染照片列表宏-->
{% macro photo_card(photo) %}
    <div class="photo-card card">
        <a href="{{ url_for('main.show_photo',photo_id=photo.id) }}" class="card-thumbnail">
            <img src="{{ url_for('main.get_image',filename=photo.filename_s) }}" class="card-img-top portrait">
        </a>
        <div class="card-body">
            <span class="oi oi-star"></span>{{ photo.collectors|length }}
            <span class="oi oi-comment-square"></span>{{ photo.comments|length }}
        </div>
    </div>
{% endmacro %}

<!--渲染用户列表宏-->
{% macro user_card(user) %}
    <div class="user-card text-center">
        <a href="{{ url_for('user.index',username=user.username) }}">
            <img src="{{ url_for('main.get_avatar',filename=user.avatar_m) }}" class="rounded avatar-m">
        </a>
        <h6>
            <a href="{{ url_for('user.index',username=user.username) }}">{{ user.name }}</a>
        </h6>
        {{ follow_area(user) }}
    </div>
{% endmacro %}

<!--渲染关注功能区域宏-->
{% macro follow_area(user) %}
    {% if current_user.is_authenticated %}
        {% if user!=current_user %}
            {% if current_user.is_following(user) %}
                <form method="post" action="{{ url_for('user.unfollow',username=user.username,next=request.full_path) }}" class="inline">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button class="btn btn-dark btn-sm" type="submit">取关</button>
                    {% if current_user.is_followed_by(user) %}
                        <p class="badge badge-light">互相关注</p>
                    {% endif %}
                </form>
            {% else %}
                <form class="inline" method="post"
                      action="{{ url_for('user.follow', username=user.username, next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-primary btn-sm">关注</button>
                    {% if current_user.is_followed_by(user) %}
                        <p class="badge badge-light">关注了你</p>
                    {% endif %}
                </form>
            {% endif %}
        {% endif %}
    {% else %}
        <form action="{{ url_for('user.follow',username=user.username) }}" class="inline" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button class="btn btn-primary btn-sm" type="submit">关注</button>
        </form>
    {% endif %}
{% endmacro %}